[workspace]
resolver = "2"
members = [
    "media_gateway_client",
    "media_gateway_server"
]

[workspace.dependencies]
savant_core = { git = "https://github.com/insight-platform/savant-rs", tag = "0.2.30" }

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Ivan Kudriavtsev <ivan.a.kudryavtsev@gmail.com>", "Ksenia Vazhdaeva <vazhdaeva_ks@bw-sw.com"]
description = "Media Gateway (client and server)"
homepage = "https://github.com/insight-platform/MediaGateway"
repository = "https://github.com/insight-platform/MediaGateway"
readme = "README.md"
rust-version = "1.78"
