networks:
  multi-stream-source:

services:
  media-gateway-server:
    image: media-gateway-server:latest
    networks:
      multi-stream-source:
        aliases:
          - media-gateway-server
    ports:
      - 8080:8080
    volumes:
      - /tmp:/tmp
      - ./config/server_config.json:/opt/etc/config.json

  media-gateway-client:
    image: media-gateway-client:latest
    networks:
      multi-stream-source:
        aliases:
          - media-gateway-client
    depends_on:
      - nginx
    volumes:
      - /tmp:/tmp
      - ./config/client_nginx_config.json:/opt/etc/config.json
      - ./ca/ca.crt:/etc/certs/ca.crt
      - ./ca/certs/client.crt:/etc/certs/client.crt
      - ./ca/certs/client.key:/etc/certs/client.key

  nginx:
    image: nginx
    networks:
      multi-stream-source:
        aliases:
          - nginx
    depends_on:
      - media-gateway-server
    ports:
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./ca/ca.crt:/etc/certs/ca.crt
      - ./ca/certs/nginx.crt:/etc/certs/nginx.crt
      - ./ca/certs/nginx.key:/etc/certs/nginx.key

  source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
    entrypoint: /opt/savant/adapters/gst/sources/multi_stream.sh
    networks:
      multi-stream-source:
        aliases:
          - source
    depends_on:
      - nginx
    environment:
      - ZMQ_ENDPOINT=req+connect:ipc:///tmp/client
      - LOCATION=/data/file_example_MP4_1280_10MG.mp4
      - SOURCE_ID=multi-stream-source-benchmark
      - DOWNLOAD_PATH=/tmp/download
      - SYNC_OUTPUT=true
      - SOURCE_ID_PATTERN='%d'
      - NUMBER_OF_STREAMS=128
    volumes:
      - /tmp:/tmp
      - ./assets/file_example_MP4_1280_10MG.mp4:/data/file_example_MP4_1280_10MG.mp4
