networks:
  video-loop:

services:
  media-gateway-server:
    image: media-gateway-server:latest
    networks:
      video-loop:
        aliases:
          - media-gateway-server
    ports:
      - 8080:8080
    volumes:
      - /tmp:/tmp
      - ./config/server_config.json:/opt/etc/config.json

  media-gateway-client:
    image: media-gateway-client:latest
    networks:
      video-loop:
        aliases:
          - media-gateway-client
    depends_on:
      - media-gateway-server
    volumes:
      - /tmp:/tmp
      - ./config/client_config.json:/opt/etc/config.json

  source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
    entrypoint: /opt/savant/adapters/gst/sources/video_loop.sh
    networks:
      video-loop:
        aliases:
          - source
    depends_on:
      - media-gateway-client
    environment:
      - ZMQ_ENDPOINT=req+connect:ipc:///tmp/client
      - LOCATION=/data/file_example_MP4_1280_10MG.mp4
      - SOURCE_ID=video-loop-benchmark
      - DOWNLOAD_PATH=/tmp/download
    volumes:
      - /tmp:/tmp
      - ./assets/file_example_MP4_1280_10MG.mp4:/data/file_example_MP4_1280_10MG.mp4
