name: Docker build & publish

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Define metadata (tags) for Docker
        id: meta
        run: |
          TAG="latest"
          if [ "${{ github.ref_type }}" == "tag" ]; then
            TAG=${{ github.ref_name }}
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Build and push Docker server image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/media-gateway-server:${{ steps.meta.outputs.tag}}
          build-args: |
            TYPE=server
      - name: Build and push Docker client image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/media-gateway-client:${{ steps.meta.outputs.tag}}
          build-args: |
            TYPE=client
