name: Rust build & test

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo sh -e build/install-deps.sh
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --test-threads 1
